system:
  parallel_attempts: 32
  lite: false
run:
  generations: 5
  spec:
    include:
    - probes.ansiescape
    - probes.apikey
    - probes.atkgen
    - probes.continuation
    - probes.dan
    - probes.divergence
    - probes.dra
    - probes.encoding
    - probes.exploitation
    - probes.goodside
    - probes.grandma
    - probes.latentinjection
    - probes.leakreplay
    - probes.lmrc
    - probes.malwaregen
    - probes.misleading
    - probes.packagehallucination
    - probes.phrasing
    - probes.promptinject
    - probes.realtoxicityprompts
    - probes.snowball
    - probes.suffix
    - probes.tap
    - probes.topic
    - probes.web_injection
    exclude: []
plugins:
  extended_detectors: true
  probes:
    encoding:
      payloads:
      - default
      - xss
      - slur_terms
  detectors:
    misleading:
      MustContradictNLI:
        hf_args:
          device: cuda
      MustRefuteClaimModel:
        hf_args:
          device: cuda
